// Generated by scripts/build-world-map-v4-runtime-assets.mjs. Do not edit by hand.
export const WORLD_MAP_V4_ASSETS = Object.freeze({
  "terrain-panel-0-0": Object.freeze({ src: "/assets/world/sound-archive-garden-v4/runtime/terrain-panel-0-0.webp", width: 960, height: 960, hasAlpha: false, category: "terrain-panel", bytes: 152466, decodedRGBA: 3686400 }),
  "terrain-panel-0-1": Object.freeze({ src: "/assets/world/sound-archive-garden-v4/runtime/terrain-panel-0-1.webp", width: 960, height: 960, hasAlpha: false, category: "terrain-panel", bytes: 147616, decodedRGBA: 3686400 }),
  "terrain-panel-0-2": Object.freeze({ src: "/assets/world/sound-archive-garden-v4/runtime/terrain-panel-0-2.webp", width: 960, height: 960, hasAlpha: false, category: "terrain-panel", bytes: 147026, decodedRGBA: 3686400 }),
  "terrain-panel-0-3": Object.freeze({ src: "/assets/world/sound-archive-garden-v4/runtime/terrain-panel-0-3.webp", width: 960, height: 960, hasAlpha: false, category: "terrain-panel", bytes: 156590, decodedRGBA: 3686400 }),
  "terrain-panel-1-0": Object.freeze({ src: "/assets/world/sound-archive-garden-v4/runtime/terrain-panel-1-0.webp", width: 960, height: 960, hasAlpha: false, category: "terrain-panel", bytes: 168964, decodedRGBA: 3686400 }),
  "terrain-panel-1-1": Object.freeze({ src: "/assets/world/sound-archive-garden-v4/runtime/terrain-panel-1-1.webp", width: 960, height: 960, hasAlpha: false, category: "terrain-panel", bytes: 133666, decodedRGBA: 3686400 }),
  "terrain-panel-1-2": Object.freeze({ src: "/assets/world/sound-archive-garden-v4/runtime/terrain-panel-1-2.webp", width: 960, height: 960, hasAlpha: false, category: "terrain-panel", bytes: 133026, decodedRGBA: 3686400 }),
  "terrain-panel-1-3": Object.freeze({ src: "/assets/world/sound-archive-garden-v4/runtime/terrain-panel-1-3.webp", width: 960, height: 960, hasAlpha: false, category: "terrain-panel", bytes: 155990, decodedRGBA: 3686400 }),
  "terrain-panel-2-0": Object.freeze({ src: "/assets/world/sound-archive-garden-v4/runtime/terrain-panel-2-0.webp", width: 960, height: 960, hasAlpha: false, category: "terrain-panel", bytes: 149868, decodedRGBA: 3686400 }),
  "terrain-panel-2-1": Object.freeze({ src: "/assets/world/sound-archive-garden-v4/runtime/terrain-panel-2-1.webp", width: 960, height: 960, hasAlpha: false, category: "terrain-panel", bytes: 148628, decodedRGBA: 3686400 }),
  "terrain-panel-2-2": Object.freeze({ src: "/assets/world/sound-archive-garden-v4/runtime/terrain-panel-2-2.webp", width: 960, height: 960, hasAlpha: false, category: "terrain-panel", bytes: 147468, decodedRGBA: 3686400 }),
  "terrain-panel-2-3": Object.freeze({ src: "/assets/world/sound-archive-garden-v4/runtime/terrain-panel-2-3.webp", width: 960, height: 960, hasAlpha: false, category: "terrain-panel", bytes: 145960, decodedRGBA: 3686400 }),
  "landmark-home": Object.freeze({ src: "/assets/world/sound-archive-garden-v4/runtime/landmark-home.webp", width: 816, height: 597, hasAlpha: true, category: "landmark", bytes: 110690, decodedRGBA: 1948608 }),
  "landmark-lab": Object.freeze({ src: "/assets/world/sound-archive-garden-v4/runtime/landmark-lab.webp", width: 1247, height: 710, hasAlpha: true, category: "landmark", bytes: 210242, decodedRGBA: 3541480 }),
  "landmark-animal": Object.freeze({ src: "/assets/world/sound-archive-garden-v4/runtime/landmark-animal.webp", width: 910, height: 663, hasAlpha: true, category: "landmark", bytes: 169032, decodedRGBA: 2413320 }),
  "landmark-nature": Object.freeze({ src: "/assets/world/sound-archive-garden-v4/runtime/landmark-nature.webp", width: 962, height: 1380, hasAlpha: true, category: "landmark", bytes: 375494, decodedRGBA: 5310240 }),
  "landmark-library": Object.freeze({ src: "/assets/world/sound-archive-garden-v4/runtime/landmark-library.webp", width: 1545, height: 717, hasAlpha: true, category: "landmark", bytes: 249172, decodedRGBA: 4431060 }),
  "landmark-urban": Object.freeze({ src: "/assets/world/sound-archive-garden-v4/runtime/landmark-urban.webp", width: 778, height: 962, hasAlpha: true, category: "landmark", bytes: 180330, decodedRGBA: 2993744 }),
  "landmark-human": Object.freeze({ src: "/assets/world/sound-archive-garden-v4/runtime/landmark-human.webp", width: 1194, height: 975, hasAlpha: true, category: "landmark", bytes: 309082, decodedRGBA: 4656600 }),
  "landmark-music": Object.freeze({ src: "/assets/world/sound-archive-garden-v4/runtime/landmark-music.webp", width: 976, height: 1002, hasAlpha: true, category: "landmark", bytes: 280580, decodedRGBA: 3911808 }),
  "landmark-home-hub": Object.freeze({ src: "/assets/world/sound-archive-garden-v4/runtime/landmark-home-hub.webp", width: 448, height: 384, hasAlpha: true, category: "landmark", bytes: 53806, decodedRGBA: 688128 }),
  "environment-north-forest": Object.freeze({ src: "/assets/world/sound-archive-garden-v4/runtime/environment-north-forest.webp", width: 3840, height: 571, hasAlpha: true, category: "environment-cluster", bytes: 596402, decodedRGBA: 8770560 }),
  "environment-west-stream-forest": Object.freeze({ src: "/assets/world/sound-archive-garden-v4/runtime/environment-west-stream-forest.webp", width: 955, height: 1459, hasAlpha: true, category: "environment-cluster", bytes: 399782, decodedRGBA: 5573380 }),
  "environment-east-forest": Object.freeze({ src: "/assets/world/sound-archive-garden-v4/runtime/environment-east-forest.webp", width: 950, height: 1605, hasAlpha: true, category: "environment-cluster", bytes: 412856, decodedRGBA: 6099000 }),
  "environment-central-gardens": Object.freeze({ src: "/assets/world/sound-archive-garden-v4/runtime/environment-central-gardens.webp", width: 2122, height: 1605, hasAlpha: true, category: "environment-cluster", bytes: 828122, decodedRGBA: 13623240 }),
  "environment-southwest-garden": Object.freeze({ src: "/assets/world/sound-archive-garden-v4/runtime/environment-southwest-garden.webp", width: 1525, height: 1130, hasAlpha: true, category: "environment-cluster", bytes: 495590, decodedRGBA: 6893000 }),
  "environment-southeast-garden": Object.freeze({ src: "/assets/world/sound-archive-garden-v4/runtime/environment-southeast-garden.webp", width: 1454, height: 1183, hasAlpha: true, category: "environment-cluster", bytes: 493110, decodedRGBA: 6880328 }),
  "environment-south-center-garden": Object.freeze({ src: "/assets/world/sound-archive-garden-v4/runtime/environment-south-center-garden.webp", width: 1061, height: 425, hasAlpha: true, category: "environment-cluster", bytes: 119478, decodedRGBA: 1803700 }),
  "environment-south-forest": Object.freeze({ src: "/assets/world/sound-archive-garden-v4/runtime/environment-south-forest.webp", width: 1936, height: 520, hasAlpha: true, category: "environment-cluster", bytes: 267698, decodedRGBA: 4026880 }),
  "foreground-south-gate": Object.freeze({ src: "/assets/world/sound-archive-garden-v4/runtime/foreground-south-gate.webp", width: 975, height: 441, hasAlpha: true, category: "foreground", bytes: 101072, decodedRGBA: 1719900 }),
})

export const WORLD_MAP_V4_ASSET_IDS = Object.freeze(Object.keys(WORLD_MAP_V4_ASSETS))

export const WORLD_MAP_V4_PREVIEW = Object.freeze({ src: "/assets/world/sound-archive-garden-v4/runtime/terrain-preview.webp", width: 480, height: 360, bytes: 29190, decodedRGBA: 691200 })

