from pathlib import Path
import json,html
out=Path(__file__).resolve().parent
v=json.loads((out/'validation.json').read_text())
rows=''.join(f"<tr><td>{r['block']}</td><td>{r['available']}</td><td>{r['A']} / {r['shortfallA']}</td><td>{r['B']} / {r['shortfallB']}</td></tr>" for r in v['capacity'])
style='''body{margin:0;background:#101b23;color:#e4e6de;font:16px/1.65 system-ui,sans-serif}main{max-width:1180px;margin:auto;padding:32px 24px}h1{font-size:32px;margin:8px 0}h2{font-size:23px;color:#d3bc8e;margin:36px 0 12px}a{color:#8aceca}p{max-width:900px}.tag{color:#d3bc8e;letter-spacing:.15em;font-size:12px}.alert{border-left:3px solid #e9b789;background:#253039;padding:18px}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:20px}.mobile{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:20px}figure{margin:0}img,object{width:100%;height:auto;display:block;border:1px solid #354854;border-radius:8px}object{aspect-ratio:4/3}figcaption{font-size:13px;color:#adbbc1;padding:8px 0 20px}table{border-collapse:collapse;width:100%;max-width:800px}td,th{padding:10px;border-bottom:1px solid #354854;text-align:left}code{font-size:13px;overflow-wrap:anywhere}li{margin:8px 0}@media(max-width:650px){main{padding:20px 14px}h1{font-size:25px}.grid{grid-template-columns:1fr}.mobile{grid-template-columns:1fr 1fr}}'''
def fig(file,caption):
 tag=f'<object data="{file}" type="image/svg+xml" aria-label="{caption}"></object>' if file.endswith('.svg') else f'<img src="{file}" alt="{caption}" loading="lazy">'
 return f'<figure><a href="{file}">{tag}</a><figcaption>{caption}</figcaption></figure>'
page=f'''<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>LAB RESET 2 · 검토 보드</title><style>{style}</style></head><body><main><span class="tag">SOUND VILLAGE / LAB RESET 02</span><h1>컨셉은 그대로, 플레이 조건은 검증 중</h1><p>콘셉트 이미지 기반의 격리 플레이 검증이며, 최종 runtime 에셋이나 production 구현이 아니다.</p><p><a href="/">플레이 preview로 이동 →</a> · <a href="detail.html">상세 보고서 원문</a></p><div class="alert"><b>필수 연결 경로 개발용 이동 완료 · A/B 전체 수용 미충족</b><br>기본 후보58개, 접근폭64 추가 검사 통과56개. 엄격 기준 A28개 / B29개 부족. 지원 공간과 주변 배치를 다시 검토해야 한다. 원본 이미지·production 수정 없음.</div>
<h2>01 · 원본 공간의 보존</h2>{fig('desktop-overview.jpg','RESET-1 환경 그대로. 중앙 프레임·석벽·연구 구역·조명을 축소하거나 교체하지 않았다.')}
<h2>02 · 접지와 가림을 분리</h2><div class="grid">{fig('logical-plan.svg','주황: 임시 지상 collision / 민트: 필수 연결 경로와 접근 영역')}{fig('foreground-plan.svg','보라: 원본을 다시 그리는 임시 상부 마스크. 직사각 마스크는 과잉 가림 가능.')}{fig('whitebox-delta.svg','분홍 점선: 옛 whitebox 연구실 / 민트: RESET-2 구역 후보. 이전108좌표를 강제하지 않는다.')}{fig('character-anchor.svg','외부72×88 / 내부72×72 / collision22×28 / 논리 foot anchor 관계')}</div>
<h2>03 · 브라우저에서 확인한 범위</h2><p>입구 → 중앙 전면 → 서측 회랑 → Archive → 복귀를 실제 RAF·collision 기반 개발용 경로 재생으로 완료했다. 단일 키보드/방향 버튼, 벽·책상·중앙 받침 collision, 로컬 출구/marker 안내도 확인했다. 전체 경로를 사람이 직접 주행한 검수와 실제 휴대폰 long press는 남아 있다.</p><div class="grid">{fig('desktop-logical-overlay.jpg','플레이 UI의 collision / 검증 범위 overlay')}{fig('desktop-frame-occlusion.jpg','프레임 뒤 캐릭터가 가려진다. 초기 감사 중 스크린샷으로 표시 수량은 중간본이다.')}</div><p><a href="browser-path-final.txt">최종 경로·loop 로그</a> · <a href="browser-checks-final.json">조작·카메라 관찰 기록</a> · <a href="tests.json">8개 논리 테스트</a></p>
<h2>04 · 카메라 비교</h2><div class="grid">{fig('desktop-fixed.jpg','Desktop 고정768×576')}{fig('desktop-recommended.jpg','같은 위치 추천: 북쪽 offset. 가장 높은 프레임 끝은 여전히 잘린다.')}</div><div class="mobile">{fig('mobile-390-legacy.jpg','390 현행:284×576world, 몸40.4px. 회랑과 조작부가 잘린다.')}{fig('mobile-390-recommended.jpg','390 추천:640×533world, 몸17.9px. 회랑+방향 조작부를 함께 표시.')}{fig('mobile-320-recommended.jpg','320 추천:몸14.5px, active링18.4px. 식별성 한계.')}</div><div class="grid">{fig('mobile-390-archive.jpg','Archive 진입부와 연구 설비가 같은 화면에 연결된다.')}{fig('mobile-landscape.jpg','가로844×390: 현재 검토 UI의 세로 길이가 커 지도·조작 동시 노출 미충족.')}</div><p>추천 후보는 desktop24×18tile+최대100world 전방offset, mobile640world/6:5 지도 영역. 320식별성과 가로UI는 미해결이며 최종 카메라 승인이 아니다. 화면 크기는 실제 휴대폰이 아닌 브라우저 viewport로 검사했다.</p>
<h2>05 · 전체 수용량</h2><table><thead><tr><th>Block</th><th>후보</th><th>A 필요 / 부족</th><th>B 필요 / 부족</th></tr></thead><tbody>{rows}</tbody></table><p>중심32world 여백, 후보 간64world, 64world 길이 접근 시player 통과, 전경 제외, 주 통로 예약을 적용했다. 추가 폭64world swept 접근 검사에서는56개만 통과했다(B1~6:13/2/13/11/13/4). B2·B5 각1개는 미달이며 preview의 주황 ×로 표시한다. 모든 후보의 실제 접근·최종 아트 검수는 남아 있다.</p>{fig('slot-plan.svg','후보58개. 민트 사각은 중심 주변64×64 여백. 169개 동시 배치가 아니다.')}<p><a href="browser-group-block-switches.json">A/B×6block 실제 UI 전환</a> · <a href="camera-density-audit.json">432개 카메라·위치·상태 정적 밀도</a></p>
<h2>06 · 다음 수정은 주변부터</h2><ol><li>남서·남동 지원 공간의 측면 개구부와 실제 통행폭을 정밀 검토한다.</li><li>같은 block 내 회랑/지원 공간 재배분을 먼저 비교한다. 현재 휴리스틱67개 전역packing도 전체 수용을 해결하지 못했다.</li><li>남서 책상/기기대, 남동 긴 작업대와 divider 끝 개구부만 최소 조정 시안을 만든다. 중앙 프레임 크기와 연구실 밀도는 유지한다.</li></ol><p>이 수정으로 부족분이 모두 해결된다고 아직 단정하지 않는다. 구조 시안 승인 → 동일 조건 재감사 → 시험 구간 clean plate·정확한 alpha 분리 순서가 필요하다.</p>
<h2>07 · 보존과 승인 대기</h2><p>기존9,945개 파일 해시 검사: 수정0 / 삭제0. 새 폴더와 보고서만 생성. Music·production·metadata·DB·Git 쓰기 없음. 최종 에셋 제작과 production 적용은 시작하지 않는다.</p><p><a href="preservation-check.json">보존 검사</a> · <a href="file-manifest.json">산출물 목록</a> · <a href="desktop-grayscale.jpg">회색조 보기 (emissive off 아님)</a></p></main></body></html>'''
(out/'report.html').write_text(page)
(out/'detail.html').write_text('<!doctype html><html lang="ko"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>LAB RESET 2 상세 보고서</title><style>'+style+'pre{white-space:pre-wrap;overflow-wrap:anywhere;font:15px/1.8 system-ui}</style><main><a href="report.html">검토 보드로 돌아가기</a><pre>'+html.escape((out.parent.parent/'LAB_RESET_2_PLAYSPACE_VALIDATION.md').read_text())+'</pre></main></html>')
char='''<svg xmlns="http://www.w3.org/2000/svg" width="800" height="600" viewBox="0 0 800 600"><rect width="800" height="600" fill="#14232d"/><g font-family="sans-serif" fill="#e7e4d9"><text x="40" y="45" font-size="24">CHARACTER / FOOT ANCHOR</text><rect x="180" y="110" width="216" height="264" fill="none" stroke="#eeeeee" stroke-width="3"/><rect x="180" y="134" width="216" height="216" fill="#5f88b855" stroke="#8abada"/><rect x="255" y="290" width="66" height="84" fill="#d0ef6344" stroke="#cdea83" stroke-width="3"/><circle cx="288" cy="374" r="8" fill="#ffe088"/><text x="430" y="130" font-size="20">72 × 88 display</text><text x="430" y="180" font-size="20">72 × 72 inner frame</text><text x="430" y="310" font-size="20">22 × 28 collision</text><text x="430" y="380" font-size="20">foot (x, y)</text><text x="40" y="455" font-size="18">display origin = (x−36, y−88)</text><text x="40" y="490" font-size="18">frame origin = (x−36, y−80)</text><text x="40" y="525" font-size="18">collision origin = (x−11, y−28)</text><text x="40" y="565" font-size="15">Inner frame includes transparent padding. Visible foot is above anchor.</text></g></svg>'''
(out/'character-anchor.svg').write_text(char)
old=json.loads((out.parent/'lab-reset-1/whitebox-snapshot.json').read_text()); s=['<svg xmlns="http://www.w3.org/2000/svg" width="1536" height="1152" viewBox="0 0 1536 1152"><image href="../lab-reset-1/environment-world.png" width="1536" height="1152"/>']
for name,b in old['STRUCTURES'].items():
 x,y,w,h=[b[k]*32 for k in ['x','y','w','h']];s.append(f'<rect x="{x}" y="{y}" width="{w}" height="{h}" fill="#f375aa22" stroke="#ff94c1" stroke-width="5" stroke-dasharray="15 10"/><text x="{x+12}" y="{y+30}" fill="white" font-size="24">OLD {name}</text>')
f=1536/1448
for name,b in [('NEW Archive',(69,236,461,384)),('NEW Spectrum',(445,144,551,224)),('NEW Signal',(951,236,427,382))]:
 x,y,w,h=[z*f for z in b];s.append(f'<rect x="{x}" y="{y}" width="{w}" height="{h}" fill="#71eac01a" stroke="#8cffe2" stroke-width="4"/><text x="{x+12}" y="{y+h-15}" fill="#c8fff1" font-size="24">{name}</text>')
s.append('</svg>');(out/'whitebox-delta.svg').write_text(''.join(s))
print('review page and two diagrams written')
