import * as G from './geometry.mjs';
const $=id=>document.getElementById(id),canvas=$('map'),ctx=canvas.getContext('2d'),stage=$('stage');
const flags={marker:true,collision:false,walkable:false,foreground:false,clearance:false,grid:false,anchor:false,scope:false,gray:false,occlusion:true};
const names={marker:'Mock marker',collision:'Collision',walkable:'통행 바닥',foreground:'전경 마스크',clearance:'Slot 여백',grid:'32px 격자',anchor:'발·충돌 box',scope:'시험 범위',gray:'Grayscale',occlusion:'전경 재합성'};
for(const [k,n] of Object.entries(names)){const l=document.createElement('label'),i=document.createElement('input');i.type='checkbox';i.checked=flags[k];i.id='toggle-'+k;i.onchange=()=>flags[k]=i.checked;l.append(i,n);$('toggles').append(l);}
const image=src=>new Promise((resolve,reject)=>{let i=new Image();i.onload=()=>resolve(i);i.onerror=()=>reject(Error('Image failed: '+src));i.src=src;});
const [env,body,clothes,hair,slots,validation,widthAudit]=await Promise.all([image('/reference/environment.png'),image('/reference/body.png'),image('/reference/clothes.png'),image('/reference/hair.png'),fetch('slots.json').then(r=>r.json()),fetch('validation.json').then(r=>r.json()),fetch('approach-width-audit.json').then(r=>r.json())]);
const narrowSlots=new Set(widthAudit.candidates.filter(s=>!s.clearDirections.length).map(s=>s.x+','+s.y));
$('capacity').textContent=`기본 후보 ${slots.length}개 / 접근폭64 통과 ${widthAudit.strictTotal}개 · A/B 전체 수용 미충족. 주황 × 두 후보는 접근폭 미달.`;
$('capacityRows').innerHTML=validation.capacity.map(c=>`<tr><td>${c.block}</td><td>${c.available}</td><td>${c.A} / ${c.B}</td><td>${c.shortfallA} / ${c.shortfallB}</td></tr>`).join('');
let p={...G.SPAWN},direction='up',keys=new Set(),cam=null,last=performance.now(),moving=false,mode='recommended',full=false,auto=null,holdUntil=0,lastHits=[],occluded=[],exitCount=0,exitWas=false,near=null,lastStatus=0,notice='',noticeUntil=0;
const history=[];let lastRecord='';
function record(event){const line=`${new Date().toISOString().slice(11,23)} ${event} (${p.x.toFixed(1)},${p.y.toFixed(1)})`;if(line.slice(13)===lastRecord)return;lastRecord=line.slice(13);history.push(line);if(history.length>160)history.shift();$('log').textContent=history.join('\n');}
function reset(){p={...G.SPAWN};auto=null;keys.clear();holdUntil=0;full=false;cam=null;exitWas=false;exitCount=0;lastHits=[];record('RESET');}
$('reset').onclick=reset;$('full').onclick=()=>{full=!full;cam=null;};$('camera').onchange=e=>{mode=e.target.value;full=false;cam=null;stage.style.aspectRatio=mode==='legacy'&&innerWidth<600?`${innerWidth}/${Math.max(400,innerHeight-56)}`:'';};
const dirs={up:[0,-1],down:[0,1],left:[-1,0],right:[1,0]};
function advance(dx,dy){const q=G.move(p,dx,dy);p={x:q.x,y:q.y};lastHits=q.hits;if(q.hits.length)record('HIT '+q.hits.join(','));moving=Boolean(dx||dy);if(Math.abs(dy)>=Math.abs(dx)&&dy)direction=dy<0?'up':'down';else if(dx)direction=dx<0?'left':'right';}
for(const b of document.querySelectorAll('[data-dir]')){const d=b.dataset.dir;b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);keys.add(d);auto=null;advance(...dirs[d].map(v=>v*G.PLAYER.speed*.01667));};b.onpointerup=b.onpointercancel=b.onlostpointercapture=()=>keys.delete(d);}
for(const b of document.querySelectorAll('[data-step]'))b.onclick=()=>{auto=null;advance(...dirs[b.dataset.step].map(v=>v*32));record('STEP '+b.dataset.step);};
const keyMap={ArrowUp:'up',ArrowDown:'down',ArrowLeft:'left',ArrowRight:'right',w:'up',s:'down',a:'left',d:'right'};
window.addEventListener('keydown',e=>{if(['SELECT','INPUT','TEXTAREA'].includes(e.target.tagName))return;const d=keyMap[e.key];if(d){e.preventDefault();auto=null;if(!keys.has(d))advance(...dirs[d].map(v=>v*G.PLAYER.speed*.01667));keys.add(d);}if(e.key==='Enter'&&near){e.preventDefault();noticeUntil=performance.now()+2500;notice=`B${near.block} mock marker 안내 — 실제 annotation 없음`;record('LOCAL ENTER B'+near.block);}});
window.addEventListener('keyup',e=>keys.delete(keyMap[e.key]));window.addEventListener('blur',()=>{keys.clear();holdUntil=0;auto=null;});document.addEventListener('visibilitychange',()=>{if(document.hidden){keys.clear();auto=null;holdUntil=0;}});
const landmarks={입구:G.SPAWN,'중앙 전면':G.point(724,751),'서측 회랑':G.point(475,478),'Archive':G.point(325,418),'프레임 뒤':G.point(724,345),'북측 접근':G.point(724,310),'동측 회랑':G.point(976,478),'장치 앞':G.point(724,710),'출구 접근':G.point(724,1025),'서측 벽 접근':G.point(470,350),'Archive 책상 옆':G.point(255,346),'첫 marker':{x:slots.find(s=>s.block===1).x,y:slots.find(s=>s.block===1).y+14}};
for(const [n,pos] of Object.entries(landmarks)){let b=document.createElement('button');b.textContent=n+' 위치';b.onclick=()=>{if(G.blocked(pos.x,pos.y)){record('INVALID LANDMARK '+n);return;}p={...pos};cam=null;auto=null;full=false;lastHits=[];record('TELEPORT '+n+' (이동 검수 아님)');};$('landmarks').append(b);}
$('route').onclick=()=>{reset();auto={path:G.ROUTE,index:1,kind:'ROUTE',stalled:0};record('DEV ROUTE START');};
$('loop').onclick=()=>{p={...G.LOOP[0]};auto={path:G.LOOP,index:1,kind:'LOOP',stalled:0};record('DEV LOOP START (시작점 이동)');};
$('stop').onclick=()=>{auto=null;keys.clear();holdUntil=0;record('STOP');};$('hold').onclick=()=>{auto=null;holdUntil=performance.now()+1000;record('DEV HOLD UP 1s');};
function path(s){ctx.beginPath();if(s.type==='rect')ctx.rect(s.x,s.y,s.w,s.h);else if(s.type==='ellipse')ctx.ellipse(s.cx,s.cy,s.rx,s.ry,0,0,Math.PI*2);else{s.points.forEach(([x,y],i)=>i?ctx.lineTo(x,y):ctx.moveTo(x,y));ctx.closePath();}}
function overlay(s,fill,stroke){path(s);ctx.fillStyle=fill;ctx.fill();ctx.strokeStyle=stroke;ctx.lineWidth=1.5;ctx.stroke();}
function marker(s,state){ctx.save();ctx.globalAlpha=state==='active'?1:state==='done'?.58:.3;ctx.strokeStyle=state==='active'?'#ffe4a7':'#9ac2d0';ctx.fillStyle='#173746';ctx.lineWidth=2;ctx.beginPath();ctx.arc(s.x,s.y,14,0,7);ctx.fill();ctx.stroke();if(state==='active'){ctx.strokeStyle='#f6f3d4';ctx.beginPath();ctx.arc(s.x,s.y,20,0,7);ctx.stroke();}ctx.fillStyle='#f5ead1';ctx.font='bold 15px system-ui';ctx.textAlign='center';ctx.fillText(state==='active'?'∿':state==='done'?'✓':'·',s.x,s.y+5);ctx.restore();}
function render(now){const dt=Math.min((now-last)/1000,.05);last=now;moving=false;stage.style.aspectRatio=full?'4 / 3':mode==='legacy'&&innerWidth<600?`${innerWidth}/${Math.max(400,innerHeight-56)}`:'';
 if(auto){const target=auto.path[auto.index],dx=target.x-p.x,dy=target.y-p.y,dist=Math.hypot(dx,dy),old={...p};if(dist<3){p={...target};record(auto.kind+' WAYPOINT '+auto.index);auto.index++;if(auto.index>=auto.path.length){record('DEV '+auto.kind+' COMPLETE');auto=null;}}else{const d=Math.min(dist,G.PLAYER.speed*dt);advance(dx/dist*d,dy/dist*d);if(Math.hypot(p.x-old.x,p.y-old.y)<.1)auto.stalled++;else auto.stalled=0;if(auto.stalled>50){record('DEV '+auto.kind+' BLOCKED');auto=null;}}}
 else{let dx=(keys.has('right')?1:0)-(keys.has('left')?1:0),dy=(keys.has('down')?1:0)-(keys.has('up')?1:0);if(now<holdUntil)dy=-1;if(dx||dy)advance(dx*G.PLAYER.speed*dt,dy*G.PLAYER.speed*dt);}
 const ex=G.inside(p.x,p.y,G.EXIT);if(ex&&!exitWas){exitCount++;record('EXIT LOCAL CONFIRM');}exitWas=ex;
 const cw=stage.clientWidth,ch=stage.clientHeight,dpr=devicePixelRatio||1;if(canvas.width!==Math.round(cw*dpr)||canvas.height!==Math.round(ch*dpr)){canvas.width=Math.round(cw*dpr);canvas.height=Math.round(ch*dpr);}
 const target=G.camera(p,full?'full':mode,cw,ch);if(!cam||full||mode==='legacy')cam=target;else{const t=1-Math.exp(-dt*8);cam={x:cam.x+(target.x-cam.x)*t,y:cam.y+(target.y-cam.y)*t,w:target.w,h:target.h};}
 ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,cw,ch);ctx.scale(cw/cam.w,ch/cam.h);ctx.translate(-cam.x,-cam.y);ctx.imageSmoothingEnabled=false;canvas.style.filter=flags.gray?'grayscale(1)':'none';ctx.drawImage(env,0,0,1536,1152);
 if(flags.walkable)overlay(G.FLOOR,'#52b49422','#95dcbc');if(flags.grid){ctx.strokeStyle='#ddf7ff22';ctx.lineWidth=1;for(let x=0;x<=1536;x+=32){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,1152);ctx.stroke();}for(let y=0;y<=1152;y+=32){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(1536,y);ctx.stroke();}}
 if(flags.collision)G.SOLIDS.forEach(s=>overlay(s,'#ff685c55','#ffaf94'));if(flags.scope)overlay(G.TEST_AREA,'#3acfac14','#97edd3');if(flags.foreground)G.OCCLUDERS.forEach(s=>overlay(s,'#a878ff55','#dfc3ff'));
 const group=$('group').value,block=Number($('block').value);let shown=[],missing=0;for(let b=1;b<=6;b++){let candidates=slots.filter(s=>s.block===b),need=validation.capacity[b-1][group];missing+=Math.max(0,need-candidates.length);shown.push(...candidates.slice(0,need).map(s=>({...s,state:b<block?'done':b===block?'active':'locked'})));}
 if(flags.clearance)for(const s of shown)overlay({type:'rect',x:s.x-32,y:s.y-32,w:64,h:64},'#70dfc520','#90efd0');
 if(flags.marker)shown.forEach(s=>{marker(s,s.state);if(narrowSlots.has(s.x+','+s.y)){ctx.strokeStyle='#ff8d64';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(s.x-11,s.y-11);ctx.lineTo(s.x+11,s.y+11);ctx.moveTo(s.x+11,s.y-11);ctx.lineTo(s.x-11,s.y+11);ctx.stroke();}});
 const row={down:0,up:1,left:3,right:2}[direction],col=moving?Math.floor(now/100)%8:0;for(const i of [body,clothes,hair])ctx.drawImage(i,col*32,row*32,32,32,p.x-36,p.y-80,72,72);
 occluded=[];for(const s of G.OCCLUDERS){if(p.y<s.depth){const b={x:p.x-17,y:p.y-55,w:34,h:48};if(G.boxHits(b,s))occluded.push(s.id);if(flags.occlusion){ctx.save();path(s);ctx.clip();ctx.drawImage(env,0,0,1536,1152);ctx.restore();}}}
 if(flags.anchor){const b=G.footBox(p.x,p.y);overlay({...b,type:'rect'},'#d2ff8522','#d2ff85');ctx.fillStyle='#faff86';ctx.fillRect(p.x-3,p.y-3,6,6);ctx.strokeStyle='#fff6';ctx.strokeRect(p.x-36,p.y-88,72,88);}
 near=shown.find(s=>s.state==='active'&&Math.hypot(s.x-p.x,s.y-(p.y-14))<40);
 if(now-lastStatus>120){lastStatus=now;$('status').textContent=`발 ${p.x.toFixed(1)}, ${p.y.toFixed(1)} · 시야 ${cam.w.toFixed(0)}×${cam.h.toFixed(0)} · 이미지 배율 ${(cw/cam.w).toFixed(3)} · 몸≈${(31.5*cw/cam.w).toFixed(1)}px · active 링 ${(40*cw/cam.w).toFixed(1)}px · EXIT ${exitCount}\n충돌 ${lastHits.join(',')||'없음'} · 가림 ${occluded.join(',')||'없음'} · ${auto?'경로 재생 중':'수동'} · ${group} 표시 ${shown.length}/${validation.capacity.reduce((n,c)=>n+c[group],0)} (부족${missing})`;
 const visible=shown.filter(s=>s.x-20>=cam.x&&s.x+20<=cam.x+cam.w&&s.y-20>=cam.y&&s.y+20<=cam.y+cam.h);
 $('density').textContent=`카메라 원점 ${cam.x.toFixed(1)}, ${cam.y.toFixed(1)} · 화면 내 완전 노출 marker active ${visible.filter(s=>s.state==='active').length} / completed ${visible.filter(s=>s.state==='done').length} / locked ${visible.filter(s=>s.state==='locked').length} · 전체 상태 ${shown.filter(s=>s.state==='active').length}/${shown.filter(s=>s.state==='done').length}/${shown.filter(s=>s.state==='locked').length}`;
 $('zonebadge').textContent=G.inside(p.x,p.y,G.TEST_AREA)?'첫 연결 구간 · 후보 평면':'그 외 구역 · 실제 검수 미완료';$('near').textContent=now<noticeUntil?notice:near?`B${near.block} mock marker 접근 · Enter 로컬 안내`:ex?'출구 도달 — 실제 화면 전환 없음':'';}
 requestAnimationFrame(render);
}
record('READY · concept-image playtest');requestAnimationFrame(render);
