// Feasibility alternatives only: no geometry or primary slot file mutation.
import fs from 'node:fs';import * as G from './geometry.mjs';
const queue=[{x:Math.round(G.SPAWN.x/8)*8,y:Math.round(G.SPAWN.y/8)*8}],seen=new Set(),k=p=>`${p.x},${p.y}`;seen.add(k(queue[0]));for(let i=0;i<queue.length;i++)for(const [dx,dy] of [[8,0],[-8,0],[0,8],[0,-8]]){const p=queue[i],t={x:p.x+dx,y:p.y+dy};if(seen.has(k(t))||G.blocked(t.x,t.y))continue;const q=G.move(p,dx,dy);if(Math.hypot(t.x-q.x,t.y-q.y)>.01)continue;queue.push(t);seen.add(k(t));}
let candidates=[];for(let y=48;y<1120;y+=16)for(let x=48;x<1500;x+=16)if(G.clearance(x,y)&&!G.reserved(x,y)&&seen.has(`${x},${y}`))candidates.push({x,y});
let best=[];for(let trial=0;trial<36;trial++){let chosen=[],list=[...candidates];const hash=p=>(((p.x+31)*73856093)^((p.y+17)*19349663)^(trial*83492791))>>>0;list.sort((a,b)=>trial<3?(trial===0?a.y-b.y||a.x-b.x:trial===1?a.x-b.x||a.y-b.y:b.y-a.y||b.x-a.x):hash(a)-hash(b));for(const p of list)if(chosen.every(q=>Math.hypot(p.x-q.x,p.y-q.y)>=64))chosen.push(p);if(chosen.length>best.length)best=chosen;}
// Region extensions preserve block order as a proposal; no forced cross-map scattering to claim PASS.
const expanded=G.BLOCK_REGIONS.map(s=>({...s}));expanded[1]={...expanded[1],y:550*G.SCALE,h:298*G.SCALE};expanded[3]={...expanded[3],h:285*G.SCALE};expanded[5]={...expanded[5],y:550*G.SCALE,h:298*G.SCALE};
const allowed=best.map(p=>({...p,blocks:expanded.flatMap((r,i)=>G.inside(p.x,p.y,r)?[i+1]:[])}));
const assignment=[],needs=[15,15,15,15,15,10];for(const p of [...allowed].sort((a,b)=>a.blocks.length-b.blocks.length)){const b=p.blocks.filter(b=>assignment.filter(q=>q.block===b).length<needs[b-1]).sort((a,b)=>(allowed.filter(q=>q.blocks.includes(a)).length-needs[a-1])-(allowed.filter(q=>q.blocks.includes(b)).length-needs[b-1]))[0];if(b)assignment.push({...p,block:b});}
const counts=needs.map((need,i)=>({block:i+1,need,assigned:assignment.filter(p=>p.block===i+1).length}));
const result={method:'36 deterministic global packings at64px, then constrained region assignment; heuristic not maximum-capacity proof',candidateGridPoints:candidates.length,bestGlobalPacking:best.length,expandedRegionCounts:counts,remainingNeed:counts.reduce((s,c)=>s+Math.max(0,c.need-c.assigned),0),geometryChanged:false,primarySlotFileChanged:false,points:assignment,proposedRegions:expanded};
fs.writeFileSync(new URL('./reallocation-review.json',import.meta.url),JSON.stringify(result,null,2));console.log(JSON.stringify({...result,points:undefined,proposedRegions:undefined},null,2));
