#!/usr/bin/env python3
"""Regenerate v4 navigation from the registered reference artwork."""

from __future__ import annotations

import base64
import json
import runpy
from pathlib import Path

import numpy as np
from PIL import Image


ROOT = Path(__file__).resolve().parents[1]
REFERENCE = ROOT / "design/world-map-v4/source-assets/world-base-clean-reference.png"
OUTPUT = ROOT / "public/assets/world/sound-archive-garden-v4"
MODULE = ROOT / "lib/worldWalkableMaskData.mjs"
REVIEW = ROOT / "_review/world-map-reference-reconstruction-v4"


def main() -> None:
    # Reuse the registered color-selection and hand-traced corrections that
    # were authored against this exact map, rather than the rejected v3 paths.
    hd_builder = runpy.run_path(str(ROOT / "scripts/build-world-map-hd-assets.py"))
    build_mask = hd_builder["registered_navigation_mask"]
    source = Image.open(REFERENCE).convert("RGB")
    raw, clearance = build_mask(source)

    OUTPUT.mkdir(parents=True, exist_ok=True)
    REVIEW.mkdir(parents=True, exist_ok=True)
    mask_image = Image.fromarray((clearance * 255).astype(np.uint8), mode="L")
    mask_image.save(OUTPUT / "walkable-clearance-mask.png", optimize=True)

    obstacle = ~clearance
    Image.fromarray((obstacle * 255).astype(np.uint8), mode="L").save(OUTPUT / "obstacle-mask.png", optimize=True)
    debug = np.zeros((clearance.shape[0], clearance.shape[1], 4), dtype=np.uint8)
    debug[:, :, :3] = np.where(clearance[:, :, None], np.array([36, 214, 96]), np.array([228, 58, 64]))
    debug[:, :, 3] = 112
    Image.fromarray(debug, mode="RGBA").save(OUTPUT / "collision-debug.png", optimize=True)

    packed = np.packbits(clearance.reshape(-1).astype(np.uint8), bitorder="little").tobytes()
    encoded = base64.b64encode(packed).decode("ascii")
    chunks = [encoded[index:index + 120] for index in range(0, len(encoded), 120)]
    body = "\n".join(f"  {chunk!r}," for chunk in chunks)
    module = f"""// Generated by scripts/build-world-map-v4-collision.py. Do not edit by hand.
export const WORLD_WALKABLE_MASK_META = Object.freeze({{
  width: 960,
  height: 720,
  cellSize: 4,
  worldWidth: 3840,
  worldHeight: 2880,
  bitOrder: 'little',
  source: 'world-map-v4-reference-registration',
}})

export const WORLD_WALKABLE_MASK_BASE64 = [
{body}
].join('')
"""
    MODULE.write_text(module, encoding="utf-8")

    report = {
        "status": "PASS",
        "source": str(REFERENCE.relative_to(ROOT)),
        "width": 960,
        "height": 720,
        "cellSize": 4,
        "rawWalkableCells": int(raw.sum()),
        "clearanceCells": int(clearance.sum()),
        "registration": {"worldWidth": 3840, "worldHeight": 2880, "referenceWidth": 2896, "referenceHeight": 2172},
    }
    (OUTPUT / "collision-build.json").write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")
    (REVIEW / "collision-build.json").write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")
    print(json.dumps(report, indent=2))


if __name__ == "__main__":
    main()
