const fs=require('fs'),sharp=require('sharp');const out='design/2d-map-redesign/previews/lab-2a-r2',assets='public/design-previews/lab-2a-r2';
const label=(w,h,title,sub='')=>Buffer.from(`<svg width="${w}" height="${h}"><rect width="100%" height="100%" fill="#172a35"/><text x="18" y="28" font-family="Arial" font-size="17" fill="#e1d1ab">${title}</text><text x="18" y="51" font-family="Arial" font-size="12" fill="#adbdc1">${sub}</text></svg>`);
(async()=>{
for(const n of ['nature','animal'])await sharp(`${out}/${n}-ui.png`).extract({left:0,top:56,width:768,height:576}).toFile(`${out}/current-${n}-768x576.png`);
async function board(name,panels){let comps=[];for(let i=0;i<panels.length;i++){comps.push({input:label(768,64,panels[i][1],panels[i][2]||'1 world pixel = 1 image pixel | 768 x 576 world viewport'),left:i*768,top:0});comps.push({input:`${out}/${panels[i][0]}`,left:i*768,top:64})}await sharp({create:{width:768*panels.length,height:640,channels:4,background:'#172a35'}}).composite(comps).png().toFile(`${out}/${name}.png`)}
await board('r1-r2-comparison',[['r1-desktop.png','R1 - geometric artwork'],['r2-desktop.png','R2 - existing sprite modules']]);await board('village-world-scale',[['current-nature-768x576.png','CURRENT NATURE'],['current-animal-768x576.png','CURRENT ANIMAL'],['r2-desktop.png','R2 ARCHIVE']]);
async function atlas(name,rows){let comps=[{input:label(1120,70,'SOURCE PIXEL AUDIT','All images keep their true pixel dimensions. No fit-to-cell normalization.'),left:0,top:0}];for(let i=0;i<rows.length;i++){let [n,world,title]=rows[i],p=`${assets}/${n}.png`,m=await sharp(p).metadata(),y=70+i*260;comps.push({input:label(1120,64,title,`${m.width}x${m.height} source | world ${m.width*world}x${m.height*world} | right: source 4x nearest`),left:0,top:y});for(const [x,sc] of [[260,1],[460,world],[740,4]])comps.push({input:await sharp(p).resize(Math.round(m.width*sc),Math.round(m.height*sc),{kernel:'nearest'}).png().toBuffer(),left:x,top:y+64})}await sharp({create:{width:1120,height:rows.length*260+80,channels:4,background:'#263945'}}).composite(comps).png().toFile(`${out}/${name}.png`)}
await atlas('source-world-integer-audit',[['source-nature-fence',2,'Nature fence: 10 source colours'],['source-animal-path',1,'Animal path: 3 source colours'],['source-table',2,'Table source: trim bounds (1,11,30,21)'],['source-shelf',2,'Storage shelf source'],['source-lamp',2,'Lamp source: trim bounds (5,6,24,26)']]);
await atlas('r2-material-corners',[['floor',2,'R2 stone floor: compressed contrast'],['desk',2,'R2 desk: native edge/centre and drawer modules'],['shelf',2,'R2 shelf: varied book groups'],['device',2,'R2 device: native stepped brass and glass']]);
console.log('Comparison boards and exact-scale asset plates ready')
})()
