const fs=require('fs'),sharp=require('sharp');const out='design/2d-map-redesign/previews/lab-2a-r3',assets='public/design-previews/lab-2a-r3',old='public/design-previews/lab-2a-r2';
const label=(w,h,title,sub='')=>Buffer.from(`<svg width="${w}" height="${h}"><rect width="100%" height="100%" fill="#172a35"/><text x="18" y="28" font-family="Arial" font-size="17" fill="#e1d1ab">${title}</text><text x="18" y="51" font-family="Arial" font-size="12" fill="#adbdc1">${sub}</text></svg>`);
(async()=>{
async function board(name,panels){let comps=[];for(let i=0;i<panels.length;i++){comps.push({input:label(768,64,panels[i][1],'1 world pixel = 1 image pixel | 768 x 576 world viewport'),left:i*768,top:0});comps.push({input:`${out}/${panels[i][0]}`,left:i*768,top:64})}await sharp({create:{width:768*panels.length,height:640,channels:4,background:'#172a35'}}).composite(comps).png().toFile(`${out}/${name}.png`)}
await board('r2-r3-comparison',[['r2-desktop.png','R2 - pixel baseline'],['r3-desktop.png','R3 - observatory identity']]);
if(fs.existsSync(`${out}/nature-ui.png`)&&fs.existsSync(`${out}/animal-ui.png`)){for(const n of ['nature','animal'])await sharp(`${out}/${n}-ui.png`).extract({left:0,top:56,width:768,height:576}).toFile(`${out}/current-${n}-768x576.png`);await board('village-world-scale',[['current-nature-768x576.png','CURRENT NATURE'],['current-animal-768x576.png','CURRENT ANIMAL'],['r3-desktop.png','R3 ARCHIVE']])}
const rows=[['device','frame','A. Column / offset observation frame'],['shelf','records','B1. Bookshelf / record storage'],['shelf','measurement','B2. Bookshelf / measurement storage'],['desk','workbench','C. Desk / observation workbench']];let comps=[],audit=[];
for(let i=0;i<rows.length;i++){const [before,after,title]=rows[i],y=i*240;comps.push({input:label(900,64,title,'R2 (left) / R3 (right) | both at world size, no normalization'),left:0,top:y});for(const [path,x]of [[`${old}/${before}.png`,180],[`${assets}/${after}.png`,540]]){let m=await sharp(path).metadata();comps.push({input:await sharp(path).resize(m.width*2,m.height*2,{kernel:'nearest'}).png().toBuffer(),left:x,top:y+90})}
let m=await sharp(`${assets}/${after}.png`).metadata();audit.push({input:label(1120,64,title,`${m.width}x${m.height} source 1x | ${m.width*2}x${m.height*2} world 2x | source 4x nearest`),left:0,top:y});for(const [x,sc]of [[260,1],[460,2],[740,4]])audit.push({input:await sharp(`${assets}/${after}.png`).resize(m.width*sc,m.height*sc,{kernel:'nearest'}).png().toBuffer(),left:x,top:y+64})}
await sharp({create:{width:900,height:960,channels:4,background:'#263945'}}).composite(comps).png().toFile(`${out}/objects-r2-r3.png`);await sharp({create:{width:1120,height:960,channels:4,background:'#263945'}}).composite(audit).png().toFile(`${out}/source-world-integer.png`);
console.log('R3 plates ready')
})()
